name: Deploy OneStop API

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  cd:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Deploy through SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -eu

            cd "${{ secrets.PROJECT_PATH }}"

            git fetch origin main
            git reset --hard origin/main

            pnpm install --frozen-lockfile
            pnpm build
            pnpm prune --prod

            pm2 reload api --update-env
            pm2 save
